### PR TITLE
fix: permission denied error from firestore emulator

### PR DESCRIPTION
**Pull request by athakor**
`PERMISSION_DENIED: Metadata operations require admin authentication.`

### CODE REVIEW

**Comment by rahulKQL** [comment]
Can we not configure NoCredentials when the user uses emulator environment variable?

**Review by rahulKQL — CHANGES_REQUESTED** [review]
I looked over the issue, To me enabling credential does not seems like proper solution to the stated problem.

**Comment by rahulKQL** [comment]
Enabling credential in ClientContext without user consent can lead to really unknown scenario, I would suggest you to discuss with Ben in that thread before raising this PR.

**Comment by athakor** [comment]
> I looked over the issue, To me enabling credential does not seems like proper solution to the stated problem.

I think yet you haven't understand the exact issue.The issue is like we need to add a dummy Authorization header to firestore requests when the emulator is enabled. And i think you haven't check what `options.getCredentials()` returns. It's return instance of `FakeCredentials` class and please check the use of [FakeCredentials ](https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L264)class.

**Comment by athakor** [comment]
@rahulKQL FYI Please check this [issue ](https://github.com/googleapis/google-cloud-php/issues/2197)and its solutions as well.

**Comment by rahulKQL** [comment]
> It's return instance of `FakeCredentials` class and please check the use of [FakeCredentials ](https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L264)class.

This is exact my doubt, I am sure this would work in case of the emulator, But if any existing user has configured credentials thru google env variable. Now with this change which one will take precedence? Will his app will continue to use Google Env Variable with default credential or `options.getCredentials()` Which I believe returns null in the non-emulator scenario?

**Comment by athakor** [comment]
> > It's return instance of `FakeCredentials` class and please check the use of [FakeCredentials ](https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L264)class.
> 
> This is exact my doubt, I am sure this would work in case of the emulator, But if any existing user has configured credentials thru google env variable. Now with this change which one will take precedence? Will his app will continue to use Google Env Variable with default credential or `options.getCredentials()` Which I believe returns null in the non-emulator scenario?

In the non-emulator scenario it goes here 
https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1/GrpcFirestoreRpc.java#L102

if you still have doubts then we can put one checks over there like
`.setCredentials(options.getHost().contains("localhost") ? options.getCredentials() : null)`

**Review by rahulKQL — APPROVED** [review]
I think this can handle in a better way but that would require a lot of changes in existing code. So for time being looks good to me.

**Pull request closed without merging**
